---
title: "Short-term vs. standard-term dual anti-platelet therapy after percutaneous coronary intervention in acute coronary syndromes: An updated systematic review and meta-analysis of randomized controlled trials"
format: docx
---

# Abstract

## Introduction

The optimal intensity and duration of antiplatelet therapy following percutaneous coronary intervention (PCI) for acute coronary syndromes (ACS), including ST-segment elevation myocardial infarction (STEMI) remain uncertain. Given ongoing uncertainty regarding the balance between ischemic protection and bleeding risk, we conducted a systematic review and meta-analysis to evaluate the outcomes of abbreviated dual antiplatelet therapy (DAPT) (1–3 months) followed by P2Y12 inhibitor monotherapy compared with a conventional 12-month DAPT regimen.

## Methods

MEDLINE/PubMed, Embase, and the Cochrane Central Register of Controlled Trials were systematically searched for studies comparing abbreviated DAPT (1–3 months) followed by P2Y12 inhibitor monotherapy with a standard 12-month DAPT regimen in patients undergoing PCI for ACS. The search encompassed all records from database inception to November 2025. Outcomes of interest included all-cause mortality, major or clinically significant bleeding, cardiovascular mortality, myocardial infarction, stent thrombosis, target vessel revascularization, and stroke.


